import type { Metadata } from "next";
import "./globals.css";
import {  Noto_Sans_Arabic } from "next/font/google";


import {
  Header, 
  Footer
} from "@/components/layout"


const notoSansArabic = Noto_Sans_Arabic({
  variable: "--font-sansarabic",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: " جمعية الهدى ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="ltr">
      <body
        className={`${notoSansArabic.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
