import type { Metadata } from "next";
import "./globals.css";
import {  Noto_Sans_Arabic } from "next/font/google";


import {
  Header, 
  Footer
} from "@/components/layout"
import { AuthProvider } from "@/utils/AuthContext";
// import GlobalLoading from "@/components/layout/GlobalLoading";


const notoSansArabic = Noto_Sans_Arabic({
  variable: "--font-sansarabic",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: " الهدى النبوي",
  description: "Generated by create next app",
    icons: {
    icon: "/logo.svg", 
    shortcut: "/logo.svg",
    apple: "/logo.svg", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="ltr">
      <body
        className={`${notoSansArabic.variable} antialiased`}
      >
        <AuthProvider>
          {/* <GlobalLoading /> */}
           <Header />
            {children}
           <Footer/>
        </AuthProvider>
      </body>
    </html>
  );
}
